@startuml
title UML Tutorial: Finite State Machines\nTurnstile Figure 2\nStatechart\n
[*] --> S_LOCKED : E_LOCK
            S_LOCKED: Wait for a Coin (function waitforcoin())
        S_LOCKED --> S_UNLOCKED: E_COIN
            S_UNLOCKED: Wait for pass (function waitforpass())
            S_UNLOCKED: Wait for a Coin (function waitforpass())
        S_UNLOCKED --> S_LOCKED: E_PASS
        S_UNLOCKED --> S_UNLOCKED: E_COIN/Say Thank you
@enduml