@startuml

title UML Tutorial: Finite State Machines\nTurnstile Figure 2\nLayerd Architecture\n

package "User Interface Layer" {
    [Display]
    [Keyboard]
    [Development\nConsole] #green
}

package "System Control Layer" {
    [FSM] #red
}

package "Subsystems Layer" {
    [Turnstile lock]
    [Turnstile coin acceptor]
    [Turnstile]
}

package "Hardware Abstraction Layer = HAL" {
    [Hardware IO] #grey
}
[FSM] -down-> [Turnstile]
[FSM] -down-> [Turnstile lock]
[FSM] -down-> [Turnstile coin acceptor]
[FSM] -up-> [Display]
[FSM] -up-> [Keyboard]
[FSM] -up-> [Development\nConsole]
[Turnstile] --> [Hardware IO]
[Turnstile lock] --> [Hardware IO]
[Turnstile coin acceptor] --> [Hardware IO]
[Development\nConsole] -down-> [Keyboard]
[Development\nConsole] -down-> [Display]
[Display] --> [Hardware IO]
[Keyboard] --> [Hardware IO]

@enduml
